docker kill my-running-app-001
docker kill my-running-app-002
docker kill my-running-app-003
docker kill my-running-app-004
docker kill my-running-app-005
docker kill my-running-app-006
docker kill my-running-app-007
docker kill my-running-app-008
docker kill my-running-app-009
docker kill my-running-app-010
docker kill my-running-app-011
docker kill my-running-app-012
docker kill my-running-app-013
docker kill my-running-app-014
docker kill my-running-app-015
docker kill my-running-app-016
docker kill my-running-app-017
docker kill my-running-app-018
docker kill my-running-app-019
docker kill my-running-app-020
docker kill my-running-app-021
docker kill my-running-app-022
docker kill my-running-app-023
docker kill my-running-app-024
docker kill my-running-app-025
docker kill my-running-app-026
docker kill my-running-app-027
docker kill my-running-app-028
docker kill my-running-app-029
docker kill my-running-app-030
docker kill my-running-app-031
docker kill my-running-app-032
docker kill my-running-app-033
docker kill my-running-app-034
docker kill my-running-app-035
docker kill my-running-app-036

